name: SOSSpy
options:
  bundleIdPrefix: com.chargetimer.prototype
  deploymentTarget:
    iOS: "17.0"

targets:
  SOSSpy:
    type: application
    platform: iOS
    sources:
      - SOSSpy
    entitlements:
      path: SOSSpy/SOSSpy.entitlements
    settings:
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_CFBundleDisplayName: SOSSpy
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "SOSSpy needs your location to calculate distance to home and find nearby chargers in Battery SOS mode."
      PRODUCT_BUNDLE_IDENTIFIER: com.chargetimer.prototype.SOSSpy
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
